# Generated by Django 5.0.14 on 2026-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_location_string_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
