# Generated by Django 5.0.14 on 2026-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_institution_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='registration_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
