# Generated by Django 5.0.14 on 2026-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_institution_registration_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_owner',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
