# Generated by Django 5.0.14 on 2026-06-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_institution_institution_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_owner',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
